# Name of workflow
name: Gendiff CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

env:
  CI: true
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  Diff file check CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
      - run: npm install
      - run: make lint
      - name: Run tests
        run: make test
      - name: Run tests coverage
        run: make test-coverage
